version: '3.4'

networks:
  dev:
    driver: bridge

services:
  Shopo_DB:
    container_name: Shopo_DB
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    networks:
      - dev

  catalogapi:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Backend/Services/Catalog/CatalogApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionString=Host=Shopo_DB;port=5432;database=CatalogDb;username=postgres;password=postgres;Pooling=true;"
    depends_on:
      - Shopo_DB
    networks:
      - dev
