version: '3.4'

networks:
  dev:
    driver: bridge

services:
  systemdb:
    container_name: systemdb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - dev

  basketdb:
    container_name: basketdb
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev

  Shopo_DB:
    container_name: Shopo_DB
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UserDb
      - POSTGRES_DB=CatalogDb
      - POSTGRES_DB=OrdersDb
    networks:
      - dev

  accountapi:
    container_name: accountapi
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Backend/Services/Accounts/AccountApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionString=Host=Shopo_DB;port=5432;database=UserDb;username=postgres;password=postgres;Pooling=true;"
    depends_on:
      - Shopo_DB
    networks:
      - dev

  basketapi:
    container_name: basketapi
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Backend/Services/Baskets/BasketApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    networks:
      - dev

  catalogapi:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Backend/Services/Catalog/CatalogApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionString=Host=Shopo_DB;port=5432;database=CatalogDb;username=postgres;password=postgres;Pooling=true;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - Shopo_DB
      - rabbitmq
    networks:
      - dev

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Backend/Gateway/apigateway/Dockerfile
    depends_on:
      - catalogapi
    ports:
      - "8000:80"
    networks:
      - dev

  orderapi:
    container_name: orderapi
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Backend/Services/Odering/Orders/OrderApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionString=Host=Shopo_DB;port=5432;database=OrdersDb;username=postgres;password=postgres;Pooling=true;"
    depends_on:
      - Shopo_DB
    networks:
      - dev

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
  systemapi:
    container_name: systemapi
    image: ${DOCKER_REGISTRY-}systemapi
    build:
      context: .
      dockerfile: Backend/Services/System/SystemAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://systemdb:27017"
    depends_on:
      - systemdb
    networks:
      - dev
